CREATE TABLE "shipping_customers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shipping_customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"phone" varchar(30) NOT NULL,
	"email" varchar(150),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shipping_driver" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shipping_driver_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"status" varchar(30) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shipping_order" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shipping_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(50) NOT NULL,
	"customerId" integer NOT NULL,
	"areaId" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"boxesCount" integer NOT NULL,
	"status" varchar(30) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shipping_product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shipping_product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"price" numeric(10, 2) NOT NULL,
	"discription" varchar(500),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shipping_route" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shipping_route_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(50) NOT NULL,
	"name" varchar(256) NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shipping_truck" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shipping_truck_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"model" varchar(50) NOT NULL,
	"plate_number" varchar(50) NOT NULL,
	"maxBoxes" integer NOT NULL,
	"driverId" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shipping_dispatch" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shipping_dispatch_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(50) NOT NULL,
	"date" date NOT NULL,
	"status" varchar(30) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shipping_dispatch_routes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shipping_dispatch_routes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dispatchId" integer NOT NULL,
	"routeId" integer NOT NULL,
	"boxesCount" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shipping_dispatch_orders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shipping_dispatch_orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dispatchId" integer NOT NULL,
	"orderId" integer NOT NULL,
	"boxesCount" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "example_post" RENAME TO "shipping_area";--> statement-breakpoint
DROP INDEX "name_idx";--> statement-breakpoint
ALTER TABLE "shipping_area" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "shipping_area" ADD COLUMN "routeId" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "shipping_order" ADD CONSTRAINT "shipping_order_customerId_shipping_customers_id_fk" FOREIGN KEY ("customerId") REFERENCES "public"."shipping_customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shipping_order" ADD CONSTRAINT "shipping_order_areaId_shipping_area_id_fk" FOREIGN KEY ("areaId") REFERENCES "public"."shipping_area"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shipping_truck" ADD CONSTRAINT "shipping_truck_driverId_shipping_driver_id_fk" FOREIGN KEY ("driverId") REFERENCES "public"."shipping_driver"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shipping_dispatch_routes" ADD CONSTRAINT "shipping_dispatch_routes_dispatchId_shipping_dispatch_id_fk" FOREIGN KEY ("dispatchId") REFERENCES "public"."shipping_dispatch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shipping_dispatch_routes" ADD CONSTRAINT "shipping_dispatch_routes_routeId_shipping_route_id_fk" FOREIGN KEY ("routeId") REFERENCES "public"."shipping_route"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shipping_dispatch_orders" ADD CONSTRAINT "shipping_dispatch_orders_dispatchId_shipping_dispatch_id_fk" FOREIGN KEY ("dispatchId") REFERENCES "public"."shipping_dispatch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shipping_dispatch_orders" ADD CONSTRAINT "shipping_dispatch_orders_orderId_shipping_order_id_fk" FOREIGN KEY ("orderId") REFERENCES "public"."shipping_order"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "customer_phone_idx" ON "shipping_customers" USING btree ("phone");--> statement-breakpoint
CREATE INDEX "customer_name_idx" ON "shipping_customers" USING btree ("name");--> statement-breakpoint
CREATE INDEX "driver_name_idx" ON "shipping_driver" USING btree ("name");--> statement-breakpoint
CREATE INDEX "order_name_idx" ON "shipping_order" USING btree ("name");--> statement-breakpoint
CREATE INDEX "order_areaId_idx" ON "shipping_order" USING btree ("areaId");--> statement-breakpoint
CREATE INDEX "order_code_idx" ON "shipping_order" USING btree ("code");--> statement-breakpoint
CREATE INDEX "product_name_idx" ON "shipping_product" USING btree ("name");--> statement-breakpoint
CREATE INDEX "route_code_idx" ON "shipping_route" USING btree ("code");--> statement-breakpoint
CREATE INDEX "route_name_idx" ON "shipping_route" USING btree ("name");--> statement-breakpoint
CREATE INDEX "truck_plate_idx" ON "shipping_truck" USING btree ("plate_number");--> statement-breakpoint
CREATE INDEX "dispatch_date_idx" ON "shipping_dispatch" USING btree ("date");--> statement-breakpoint
CREATE INDEX "dispatch_code_idx" ON "shipping_dispatch" USING btree ("code");--> statement-breakpoint
CREATE INDEX "dispatch_route_idx" ON "shipping_dispatch_routes" USING btree ("dispatchId","routeId");--> statement-breakpoint
CREATE INDEX "dispatch_order_idx" ON "shipping_dispatch_orders" USING btree ("dispatchId","orderId");--> statement-breakpoint
ALTER TABLE "shipping_area" ADD CONSTRAINT "shipping_area_routeId_shipping_route_id_fk" FOREIGN KEY ("routeId") REFERENCES "public"."shipping_route"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "area_route_idx" ON "shipping_area" USING btree ("routeId");--> statement-breakpoint
CREATE INDEX "area_route_name_idx" ON "shipping_area" USING btree ("routeId","name");