CREATE TABLE "shipping_order_products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shipping_order_products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"orderId" integer NOT NULL,
	"productId" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "shipping_order_products" ADD CONSTRAINT "shipping_order_products_orderId_shipping_order_id_fk" FOREIGN KEY ("orderId") REFERENCES "public"."shipping_order"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shipping_order_products" ADD CONSTRAINT "shipping_order_products_productId_shipping_product_id_fk" FOREIGN KEY ("productId") REFERENCES "public"."shipping_product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "orderId_productId_idx" ON "shipping_order_products" USING btree ("orderId","productId");